### ISSUE TITLE
MXC_SPI_Init elseif statement bugs

### ISSUE THREAD

**Issue by cblack-f3** [Analog-Devices-MSDK/msdk#196]
https://github.com/Analog-Devices-MSDK/msdk/blob/25461c92fa248083f40f04a6b3307da4cb744eb5/Libraries/PeriphDrivers/Source/SPI/spi_me18.c#L106

if statements for MXC_SPI2, 3, 4 are incomplete, missing `spi == `

**Comment by Jake-Carter** [comment]
Thanks @cblack-f3, PR opened

**Comment by cblack-f3** [comment]
We are using SPI peripheral #4 on our HW and ran into this, tried the fix and it is working ok

![DS4_QuickPrint2](https://user-images.githubusercontent.com/45828731/197306582-235b3ee5-dce4-4a35-a03b-7ef88799ccb1.png)

**Comment by Jake-Carter** [comment]
We appreciate it!  The fix has been merged into main
