### ISSUE TITLE
MXC_SPI_GetPeripheralClock: Missing break statements

### ISSUE THREAD

**Issue by cblack-f3** [Analog-Devices-MSDK/msdk#211]
https://github.com/Analog-Devices-MSDK/msdk/blob/da5a44ebf646278d4dfc5f13a22ece61a8491947/Libraries/PeriphDrivers/Source/SPI/spi_me18.c#L210

Always uses EXTCLK_FREQ due to missing break statements in this switch.  Was easy to miss as SPI still functions, just at the wrong desired frequency

**Comment by Jake-Carter** [comment]
Thanks again @cblack-f3
