### ISSUE TITLE
can't read AIN0, AIN1, ... analog inputs using HAL

### ISSUE THREAD

**Issue by buha** [Analog-Devices-MSDK/msdk#363]
Hi,

I'm trying to get some readings in with MAX32650 of AIN0, AIN1, etc. external channels.

No matter what I provide on AIN0, AIN1, pins of the FTHR board, I always get the raw value 1 as reading.

However, if I perform ADC conversions of internal channels I get meaningful values.

The seqence of calls is:
```
MXC_ADC_Init();
MXC_ADC_StartConversion(ch); // ch is MXC_ADC_CH_0, MXC_ADC_CH_1 etc.
MXC_ADC_GetData(&reading)
```
Here's the readings that I get converted to Volts using `reading * 1.22V / 1024`
```
ain0 = 0.001191 Volts
ain0/5 = 0.001191 Volts
ain1 = 0.001191 Volts
ain1/5 = 0.001191 Volts
vcore = 1.122305 Volts
vdda = 1.218809 Volts
vddb/4 = 0.795859 Volts
vddio/4 = 0.459883 Volts
vddioh/4 = 0.847090 Volts
```

First values are ALWAYS 1 * 1.22 / 1024 = 0x001191.
The rest of the values seem correct.

**Comment by buha** [comment]
nevermind, the FTHR board routes AIN0, AIN1 etc. pins to an external I2C ADC, not to the embedded ADC of the microcontroller...

**Comment by buha** [comment]
S

**Comment by buha** [comment]
@kevin-gillespie any idea ?

**Comment by buha** [comment]
Found the reason...

Board_Init() was doing nothing in my firmware and so by comparison with your example, it wasn't initializing the MXC_SYS_PERIPH_CLOCK_GPIO2 (GPIO2.3 and GPIO2.4).

https://github.com/Analog-Devices-MSDK/msdk/blob/main/Libraries/Boards/MAX78000/FTHR_RevA/Source/board.c#L85

**Comment by Jake-Carter** [comment]
Thanks @buha, can we close this?
