### ISSUE TITLE
Build error with latest gcc

### ISSUE THREAD

**Issue by kevin-gillespie** [Analog-Devices-MSDK/msdk#410]
Latest version of arm-none-eabi-gcc generates errors when building.

https://github.com/Analog-Devices-MSDK/msdk/actions/runs/4165218612/jobs/7207911293

**Comment by rotx-maxim** [comment]
I think I have the same issue with Libraries/PeriphDrivers/Include/MAX32650/mxc_lock.h.
That file needs an `#include <stdint.h>`
