### ISSUE TITLE
MSDK installation errors on Ubuntu 22.04

### ISSUE THREAD

**Issue by plat-zhaw** [Analog-Devices-MSDK/msdk#516]
Hi there,

I downloaded and installed the Maxim Micros SDK on Ubuntu 22.04. I got two different errors.

The first error occurs when the installer tries to make the directory for the links on the desktop. I simply ignored the first message `Error: Operation MkDir does not exist.`. The second message `Error during installation process (com.maximintegrated.intaller): Execution failed (Unexpected exit code: 1) "ln -s /home/plat/MaximSDK /home/plat/Desktop/MaximSDK/MaximSDK"` shows the path of the missing directory. I simply created the directory `/home/plat/Desktop/MaximSDK/MaximSDK` manually. Then I pressed the button `Retry` and it created the link. 

![maxim_msdk_install_error_mkdir_0](https://user-images.githubusercontent.com/72737183/228203272-2fcc97e4-c8da-4408-94bb-aa12b2bdf3f8.png)
![maxim_msdk_install_error_mkdir_1](https://user-images.githubusercontent.com/72737183/228203275-05c5beee-e00a-41c5-8772-e29f4432900e.png)

The second error is about the Eclipse application launcher. The error messages below show that the installer tries to access the file `/usr/share/applications/Eclipse-MaximSDK.desktop`. So I went to the the parent folder to try and assign the file the correct permissions as shown in the second error message, but there is no such file in there, as the bash transcript below shows.

```bash
plat@6674:/usr/share/applications$ ls -al | grep -i maxim
plat@6674:/usr/share/applications$ ls -al | grep -i eclipse
plat@6674:/usr/share/applications$ 
```

![maxim_msdk_install_error_permission_denied_0](https://user-images.githubusercontent.com/72737183/228205401-8525f640-6c2b-4e43-8758-0ec939042ea0.png)
![maxim_msdk_install_error_permission_denied_1](https://user-images.githubusercontent.com/72737183/228205407-9f91cc20-be5e-4847-9f93-2144624c7440.png)

I could solve the first error. The second error just means that the application launcher for the Eclipse application is missing. I do not plan to use this. I much rather use VS Code anyway. I just hope there will be no problems down the line.

Kind regards.

**Comment by Jake-Carter** [comment]
Hi @plat-zhaw, thank you very much for reporting this.
* Error 1:  This is a typo in our installer package.  It should be `Mkdir` instead of `MkDir`.
* Error 2: The installer needs elevated permissions to write to `/usr/share/...`, but we are missing a call to elevate this operation.

I'll be pushing fixes to our installer package to address these bugs.  You're right, the SDK should be fully functional despite the missing Eclipse shortcut.

**Comment by plat-zhaw** [comment]
Hi @Jake-Carter, thanks for the fast answer. I am glad that the SDK should be usable. That is the most important thing for me.

**Comment by Jake-Carter** [comment]
Updated component files have now been pushed to the release server.  As of 4/20/2023 this issue should be fixed.

Thanks again for reporting @plat-zhaw
