### ISSUE TITLE
MXC_SYS Missing EXT_CLK Support

### ISSUE THREAD

**Issue by jlj-ee** [Analog-Devices-MSDK/msdk#518]
Hi, is there a bug in the MXC_SYS implementation for the MAX32670?

In the [UG](https://www.analog.com/media/en/technical-documentation/user-guides/max32670max32671-user-guide.pdf), the clock tree (page 38) and GCR_CLKCTRL register description (page 66-67) both document an external clock as an available system clock option.
However, the implementation in sys_me15.c has support for EXTCLK removed:

In MXC_SYS_ClockSourceEnable (returns an error)
```C
    case MXC_SYS_CLOCK_EXTCLK:
        // MXC_GCR->clkctrl |= MXC_F_GCR_CLKCTRL_EXTCLK_EN;
        // return MXC_SYS_Clock_Timeout(MXC_F_GCR_CLKCTRL_EXTCLK_RDY);
        return E_NOT_SUPPORTED;
        break;
```

In MXC_SYS_ClockSourceDisable (silent failure)
```C
    case MXC_SYS_CLOCK_EXTCLK:
        // MXC_GCR->clkctrl &= ~MXC_F_GCR_CLKCTRL_EXTCLK_EN;
        break;
```

In MXC_SYS_ClockSelect (silent failure)
```C
    case MXC_SYS_CLOCK_EXTCLK:
        // Enable HIRC clock
        // if(!(MXC_GCR->clkctrl & MXC_F_GCR_CLKCTRL_EXTCLK_EN)) {
        //     MXC_GCR->clkctrl |=MXC_F_GCR_CLKCTRL_EXTCLK_EN;

        //     // Check if HIRC clock is ready
        //     if (MXC_SYS_Clock_Timeout(MXC_F_GCR_CLKCTRL_EXTCLK_RDY) != E_NO_ERROR) {
        //         return E_TIME_OUT;
        //     }
        // }

        // Set HIRC clock as System Clock
        // MXC_SETFIELD(MXC_GCR->clkctrl, MXC_F_GCR_CLKCTRL_SYSCLK_SEL, MXC_S_GCR_CLKCTRL_SYSCLK_SEL_EXTCLK);

        break;
```

I will be populating the EXT_CLK footprint on my EV kit to test this disabled code.

(Also, MXC_SYS does not appear in the [peripheral documentation](https://analog-devices-msdk.github.io/msdk/Libraries/PeriphDrivers/Documentation/MAX32670/modules.html).)

**Comment by jlj-ee** [comment]
Thanks @Jake-Carter for looking into this! That sequence for establishing the EXT_CLK input makes sense.
I am also happy to help test on my EV Kit.

**Comment by Jake-Carter** [comment]
Hi @jlj-ee, I added EXT_CLK support for the MAX32670 and tested it at 2Mhz.  I don't have a clean enough connection to test at higher speeds, but it looks like `Hello_World` is working as expected off of the external input.

See the [`EXT_CLK`](https://github.com/Jake-Carter/msdk/tree/fix/gh-518/Examples/MAX32670/EXT_CLK) example on my fork.

I'll be porting this to the other micros as well before merging the PR.

**Comment by jlj-ee** [comment]
Hi @Jake-Carter, I got a chance to verify the example from your fork on my EVKit and it looks great!
When I have some more time I will look at additional speeds. Thanks for getting this fix in!
