### ISSUE TITLE
MAX32672 (ME17) Has "crc.h"

### ISSUE THREAD

**Issue by cpacileo** [Analog-Devices-MSDK/msdk#527]
![Screenshot (154)](https://user-images.githubusercontent.com/129331437/228655437-04a89790-88cc-4f00-9b5e-078bb0112c87.png)

Within any of the MAX32xxx peripheral drivers, the crc.h file includes crc_regs.h that cannot be found anywhere.

**Comment by Jake-Carter** [comment]
CRC functionality and registers for the MAX32672 exist in the [Cryptographic Toolbox (CTB)](https://analog-devices-msdk.github.io/msdk/Libraries/PeriphDrivers/Documentation/MAX32672/group__ctb.html) peripheral.  

`crc.h` should be removed from the MAX32672 PeriphDrivers include files.
