### ISSUE TITLE
MAX32672 Evaluation Kit - ADC Example - Increase in Current Consumption Related to Analog Input Voltage

### ISSUE THREAD

**Issue by leoreyesth** [Analog-Devices-MSDK/msdk#530]
I was performing some current measurements with the ADC and I noted an unexpected increase in the current consumption on the VDD and VDA lines that are related to the voltage level of the analog input.

The steps to reproduce the issue are the following:

1. Load the ADC example code
2. Remove jumpers JP2 through JP11
3. Disconnect LCD
4. Connect a variable voltage on pin AN3
5. Measure the current consumption of the VDD and VDA lines while changing the AN3 voltage.

Above 0.7V the current starts to ramp up and peaks at 1.6V with an increase of 0.48mA respect the baseline and then starts to go down. (See attached picture)

![image](https://user-images.githubusercontent.com/53155328/228930546-08ddd67b-ad90-47dd-97e4-5ecc78c114bd.png)

Is this behavior expected?

**Comment by Jake-Carter** [comment]
Hi @leoreyesth, this is a bit outside of the scope of the MSDK.  I would suggest reaching out to our technical support team via our [support portal](https://support.analog.com/en-US/technical-support/).

They will better be able to clarify the expected functionality of the hardware.  Please request that I (Jake Carter) be CC'd on the support communications so I can see if there are any changes needed for the ADC drivers.

Thanks,
Jake
