### ISSUE TITLE
MSDK Installer Failure

### ISSUE THREAD

**Issue by EricB-ADI** [Analog-Devices-MSDK/msdk#542]
I was installing all of our tools on a new install of ubuntu using the MSDK installer, and it seems that there is an issue with one of the commands. it looks like it used ``MkDir`` instead of ``mkdir`` in the shell. Second issue seems to be with a bad symlink. After that, seems like a chain of problems.

I'm not sure how doable it is, but if possible, we should add a workflow to test this process. 

![msdk_installer_failure](https://user-images.githubusercontent.com/122300463/230698640-5bbb4669-1604-44c2-a5a0-de51008d357c.png)
![installer_fail](https://user-images.githubusercontent.com/122300463/230698903-7da50eb8-ebde-4e72-9532-0509e6245758.png)

![permission_error](https://user-images.githubusercontent.com/122300463/230698834-d411b1a3-0fd0-4e89-9ad8-3c7bf140c790.png)

![profit??](https://user-images.githubusercontent.com/122300463/230698843-b9b6b6a9-8345-4a11-8d54-e55dbaef9748.png)

**Comment by Jake-Carter** [comment]
Thanks @EricB-ADI, this is the same issue as #516 

I've had a fix to the installer package staged for release on the test server.  Just waiting for approval to push it out to production next week.

Agreed we need some auto-testing of the installer.  It's on my task list, should be able to get to it soon

**Comment by EricB-ADI** [comment]
Alright, im gonna close this then
