### ISSUE TITLE
help finding model loader in CNN example

### ISSUE THREAD

**Issue by nikky4D** [Analog-Devices-MSDK/msdk#618]
I'm not very familiar with c so can someone point out where the model is loaded in this CNN model example: Examples/MAX78002/CNN/pascalvoc-retinanetv7_3

I don't understand the inference pipeline. I would like to attempt to change the model and load the image but I'm confused as to how to go about it with this example.

**Comment by Jake-Carter** [comment]
Hi @nikky4D I would suggest starting in our AI Documentation repo [here](https://github.com/MaximIntegratedAI/MaximAI_Documentation#readme).

I also recommend working through the [quick-start for the MAX78002EVKIT](https://github.com/MaximIntegratedAI/MaximAI_Documentation/tree/master/MAX78002_Evaluation_Kit#readme) first.  There is an ML-focused section at the end which will help put things into better context.  Especially the video series.

To directly answer your question:  The C code for the model is generated by the [ai8x-synthesis](https://github.com/MaximIntegratedAI/ai8x-synthesis) tool.  The model itself is saved as a `weights.h` header file that is loaded from flash into the CNN accelerator by the [`cnn_load_weights`](https://github.com/Analog-Devices-MSDK/msdk/blob/9c5370d8e72e0622a5f3bd1525ed0c5514e283e0/Examples/MAX78002/CNN/pascalvoc-retinanetv7_3/src/cnn/cnn.c#L209) function.

I'm happy to help clarify if you have specific questions about the example

**Comment by nikky4D** [comment]
Thank you @Jake-Carter . I've worked through several samples in ai8x-synthesis and ai8x-training and trained my models as well. However, I'm still stuck in the inference pipeline.

Precisely, how do I modify the main.c to take in camera input and pass through the model to get the outputs?

**Comment by Jake-Carter** [comment]
Happy to help!

Fundamentally, you will need to change the implementation of the `load_input` function.  By default, the output of the ai8x-synthesis tool will usually give you a `load_input` function that looks something like this:

```C
// 1-channel 28x28 data input (784 bytes / 196 32-bit words):
// CHW 28x28, channel 0
static const uint32_t input_0[] = SAMPLE_INPUT_0;

void load_input(void)
{
    // This function loads the sample data input -- replace with actual data
    memcpy32((uint32_t *)0x50400000, input_0, 196);
}
```

All this does is copy the "Known Answer Test" (KAT) into the data memory of the CNN accelerator for its input layer.

In practice, you will need to interface with real-world sensors to collect data, reformat it if necessary to match the input the model expects, then load it into the accelerator.  For most image processing models you will probably use the input FIFO for this.  (see [Camera Streaming Guide](https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/Guides/Camera_Streaming_Guide.md) for more details).  However, _where_ you do this does not change.  You will always need to load the input data from inside the `load_input` function.

For generic examples on how to use the camera, see the [CameraIF](https://github.com/Analog-Devices-MSDK/msdk/tree/main/Examples/MAX78000/CameraIF) and [ImgCapture](https://github.com/Analog-Devices-MSDK/msdk/tree/main/Examples/MAX78000/ImgCapture) examples.

For a CNN example that uses the camera as input the [digit-detection-demo](https://github.com/Analog-Devices-MSDK/msdk/tree/main/Examples/MAX78000/CNN/digit-detection-demo) is a good reference.

**Comment by Jake-Carter** [comment]
Closing this out, let us know if you have any other questions
