### ISSUE TITLE
Include paths through properties tab not working 

### ISSUE THREAD

**Issue by Furkan-Alb** [Analog-Devices-MSDK/msdk#646]
In Maxim SDK, declaring an include file or folder through properties -> C/C++ General -> Paths and Symbols results in a directory or path not found error during compiling. The error appears to have affected multiple co-workers on the team and thus is not an issue on my local device. However, including the paths using the "IPATH" and "VPATH" functions in the project.mk file compiles with no errors.

**Maxim SDK**
Version: 2022-12 (4.26.0)
Build id: 20221201-1913

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by Jake-Carter** [comment]
The Properties -> C/C++ General -> Paths and Symbols option in Eclipse is only used by its code browsing engine.  Our projects do not use Eclipse's managed build system for automatic Makefile generation, so you must manually add the entries on VPATH and IPATH as you've seen.
