### ISSUE TITLE
June 2023 Release Issues

### ISSUE THREAD

**Issue by ConWalsh** [Analog-Devices-MSDK/msdk#654]
Hello!

SDK was updated to the latest version (June 23 release) and a number of issues were encountered:

1. No _File -> New -> Maxim Microcontrollers._ in Eclipse anymore. 
![image](https://github.com/Analog-Devices-MSDK/msdk/assets/134274659/ab6061be-df68-44c0-99f9-2f88e3a0d481)

2. New build errors for previously building projects. It looks like some Source/Include folders were removed in Libraries/Boards/MAX_XXXXX that contained high level board code such as pb.c/.h for pushbuttons and led.c/.h for LEDs. 
![image](https://github.com/Analog-Devices-MSDK/msdk/assets/134274659/1056dde7-a2dd-4e87-9cb8-28b9af3d7e7e)

Code builds fine once references to these files is removed. Workaround is just to reimplement these functions.

Thanks

**Comment by ConWalsh** [comment]
Following [these steps](https://confluence.analog.com/display/PBUSPKB/Can%27t+See+Maxim+Microcontrollers+Project+in+Eclipse+Maxim+SDK+After+Update) I was able to rectify the first problem.

**Comment by Jake-Carter** [comment]
@ConWalsh you didn't miss it, I added it to the release notes thanks to your findings.  So thanks again for your report!

**Comment by Jake-Carter** [comment]
We just pushed a hotfix for the Eclipse plugin as well.

As of `1.0.4-31` the new project wizard should be fixed as well and visible in the usual spot.

![image](https://github.com/Analog-Devices-MSDK/msdk/assets/38844790/366df74c-d951-4886-a353-714159b7626e)

![image](https://github.com/Analog-Devices-MSDK/msdk/assets/38844790/37b12ca3-f5f5-465d-afc7-812298abba7c)
