### ISSUE TITLE
lwIP Library: Build system generates wrong output when PROJECT is defined in a parent Makefile

### ISSUE THREAD

**Issue by ahmetalincak** [Analog-Devices-MSDK/msdk#665]
I tried to build a lwIP example in VS Code and noticed the build error which states the liblwip_soft.a is not found. Dug down and found that VS Code's build task defines the `PROJECT` item while calling the makefile, lwIP's makefile tries to redefine the `PROJECT` item but it seems it can not without the `override` keyword.

Output which indicates the error:
```
  ...
  CC    C:/MaximSDK/Libraries/CMSIS/../lwIP/netif/ppp/polarssl/des.c
  CC    C:/MaximSDK/Libraries/CMSIS/../lwIP/netif/ppp/polarssl/md5.c
  CC    C:/MaximSDK/Libraries/CMSIS/../lwIP/netif/ppp/polarssl/sha1.c
  CC    C:/MaximSDK/Libraries/CMSIS/../lwIP/Maxim/mxc_eth.c
  AR    C:/MaximSDK/Libraries/lwIP/bin/softfp/lwIP_FreeRTOS.a

  arm-none-eabi-gcc.exe: error: C:/MaximSDK/Libraries/lwIP/bin/softfp/liblwip_softfp.a: No such file or directory 
```

**Comment by Jake-Carter** [comment]
Thanks @ahmetalincak.  I did some clean-up of the lwip library Makefiles.  It should fix the issue.

Your review and testing for #669 would be greatly appreciated.
