### ISSUE TITLE
setenv.bat sets wrong path for riscv-none-embed-gcc toolchain

### ISSUE THREAD

**Issue by emcyaman** [Analog-Devices-MSDK/msdk#677]
In the "setenv.bat" script where toolchain paths are added to the PATH environment variable:
`set PATH=%MAXIM_SBT_DIR%\bin;%TOOLCHAIN_PATH%\GNUTools\10.3\bin;%TOOLCHAIN_PATH%\xPack\riscv-none-elf-gcc\12.2.0-3.1\bin:%TOOLCHAIN_PATH%\xPack\riscv-none-embed-gcc\10.2.0-1.2\bin;%TOOLCHAIN_PATH%\MSYS2\usr\bin;%TOOLCHAIN_PATH%\OpenOCD;%PATH%`

There is a typo between `%TOOLCHAIN_PATH%\xPack\riscv-none-elf-gcc\12.2.0-3.1\bin` and `%TOOLCHAIN_PATH%\xPack\riscv-none-embed-gcc\10.2.0-1.2\bin` entries (there should be a semicolon instead of a colon). This causes a wrong path to set for riscv-none-embed-gcc toolchain.

**Comment by Jake-Carter** [comment]
Thanks @emcyaman, fixed in our packages repo.  Will push out a hotfix to the release server asap.

**Comment by lorne-maxim** [comment]
The release server and the [windows version of the offline installer](https://github.com/Analog-Devices-MSDK/msdk/releases/download/v2023_06/MaximMicrosSDK_2023_06_Windows.zip) have been updated.
