### ISSUE TITLE
RGB888_to_RGB

### ISSUE THREAD

**Issue by ryalberti** [Analog-Devices-MSDK/msdk#681]
In the file[ imgConverter.py](https://github.com/Analog-Devices-MSDK/msdk/blob/main/Examples/MAX78000/ImgCapture/utils/imgConverter.py) as seen in msdk/Examples/MAX78000/ImageCapture/utils the function rgb888_to_rgb uses 3 as the bytes per pixel. This results in a faulty conversion. The 3 should be changed to a 4 in lines 108 & 109. Attached is our fix as an example.
[imgConverter.zip](https://github.com/Analog-Devices-MSDK/msdk/files/12113144/imgConverter.zip)

**Comment by Jake-Carter** [comment]
Thanks @ryalberti, just opened a PR to fix the converter script and auto-select the correct FIFO mode for RGB888 conversions.
