### ISSUE TITLE
Feature Request: Control which peripheral drivers are built

### ISSUE THREAD

**Issue by jlj-ee** [Analog-Devices-MSDK/msdk#716]
The included Makefile system with project.mk overrides provides a great foundation and covers a lot of common cases.
But one thing I miss compared to a tool like Keil's RTE manager is the ability to select which peripheral drivers to include in my build to help manage code size:
![image](https://github.com/Analog-Devices-MSDK/msdk/assets/11401637/718b7a37-e9e5-47bf-a36b-f6e69601277f)

So far, the "easiest" way I have been able to work around this in the Makefile build system is to set LIB_PERIPHDRIVERS to 0 and then make local modified copies of periphdriver.mk, libPeriphDriver.mk, and {target}_files.mk. Am I missing a simpler approach?

Two additions to the build system could improve this:
- Variable to override in project.mk that sets the path to {target}_files.mk, to make it easier to have a local modified version
- Makefile variables that can be set via project.mk to exclude each peripheral driver that may not be needed, e.g. set LIB_PERIPHDRIVER_RTC to 0 exclude the RTC driver code.

Both additions would be useful for different reasons: the latter is more user-friendly for people less familiar with Makefiles, while the former provides more control and also makes it easier to e.g. swap in a patched version of a driver file.

A side-effect from making use of this feature would be that the built library (libPeriphDriver.a) would not be as portable across multiple projects, requiring more frequent cleans. However, this caveat could possibly be addressed by automatically resolving a local path to libPeriphDriver if the user overrides the standard {target}_files.mk.

Thoughts? Is this in scope? If so, I could take a pass at implementing this.

**Comment by Jake-Carter** [comment]
The linker does a pretty good job of only pulling in what you actually use from the PeriphDrivers, so I think this may be more effort than it's worth.  It will only affect the build size of the PeriphDrivers static library file, which is left behind post link-time.  I don't think this will have much (or any) affect on the application code size, but correct me if I'm wrong
