### ISSUE TITLE
Argument List Too Long - RISC-V AR

### ISSUE THREAD

**Issue by BrentK-ADI** [Analog-Devices-MSDK/msdk#731]
When building the Cordio library for the RISC-V on MAX32690, the AR command fails with an "Argument List too Long" error.  It looks like this was resolved in gcc.mk by using an ar_args.txt for the arguments.  This should be ported over to the RISC-V makefile as well.

**Comment by Jake-Carter** [comment]
Thanks @BrentK-ADI, looks like I fixed this issue when I synced up this GCC makefiles with each other in https://github.com/Analog-Devices-MSDK/msdk/pull/653

The release SDK doesn't have these changes yet, the development repo should fix this issue.  I'll close this out when we push the release in case anyone else hits it.

**Comment by Jake-Carter** [comment]
Closing alongside the Oct 2023 release:  https://github.com/Analog-Devices-MSDK/msdk/releases/tag/v2023_10
