### ISSUE TITLE
Redundant "if" statement in Master Async handler of I2C driver

### ISSUE THREAD

**Issue by muxx999** [Analog-Devices-MSDK/msdk#753]
Location: msdk/Libraries/PeriphDrivers/Source/I2C/i2c_reva.c
Function `MXC_I2C_RevA_MasterAsyncHandler(int i2cNum)`
Lines 1442-1447  `/* Call the callback */`

The issue does no harm just contains an if/else statement a part of which is never called.
The statement can be  replaced by single line: 
`MXC_I2C_RevA_AsyncCallback(i2c, E_NO_ERROR); `
because 1) the intfl0 flags get cleared in line 1432, so the 'if' expression is always 0,
2) the case of errors present ( `E_COMM_ERR` ) is taken care of at block 1355-1368  `/* Check for errors */`.

**Comment by Jake-Carter** [comment]
Thanks @muxx999, agreed we can remove the extra conditional
