### ISSUE TITLE
Max32690 SDK default PAL_NVM_SIZE defined in cordio.mk causes the code to enter in infinite loop when PalFlashEraseChip() function is called.

### ISSUE THREAD

**Issue by Ankitpatel2022** [Analog-Devices-MSDK/msdk#771]
With the default PAL_NVM_SIZE defined as 0x2000 in cordio.mk if the `PalFlashEraseChip()` function is called, the below while loop never gets out of it and it also tries to erase the other memory region out of defined PAL_NVM region. The root cause is MXC_FLASH_PAGE_SIZE is 0x4000 and as after the first iteration, the `size` variable becomes 0x2000-0x4000 and it is never reaches to 0 and `startAddr` variable will keep increased by offset 0x4000.
```
  while(size) {
    WsfCsEnter();
    MXC_FLC_PageErase(startAddr);
    WsfCsExit();

    startAddr += MXC_FLASH_PAGE_SIZE;
    size -= MXC_FLASH_PAGE_SIZE;
  }
```

Suggestion:
(a) Define default PAL_NVM_SIZE which is in multiple of the MXC_FLASH_PAGE_SIZE
(b) Modify `PalFlashEraseChip()` function such a way, it does erase the targeted memory only.

**Comment by Jake-Carter** [comment]
Thanks @Ankitpatel2022 

Looks like we didn't apply #726 to the MAX32690
