### ISSUE TITLE
Update request for SDHC default SPI Speed 

### ISSUE THREAD

**Issue by oguzhanbsolak** [Analog-Devices-MSDK/msdk#784]
Hi,

For the upcoming MAX78000FTHR facial recognition demo, we need a 25MHz SPI for SDHC to get a higher FPS.
Currently, this value is set to 10MHz at the SDHC/ff13/Source/diskio.c by the SPI_SPEED parameter. Is it possible to update the default value to 25MHz or add a new flag to enable high-speed spi usage for SDHC?

Regards,
Oguzhan Buyuksolak

**Comment by Jake-Carter** [comment]
We can also support this.  I'll add the ability to override the default SPI speed per-project.

**Comment by oguzhanbsolak** [comment]
Hi Jake,

Thank you for your return on these issues.

Regards,
Oğuzhan Büyüksolak

**Comment by Jake-Carter** [comment]
@oguzhanbsolak FYI this is merged.  See the PR description above for details on the new build variable
