### ISSUE TITLE
Update request for tsc2046 TS_MAX_BUTTONS

### ISSUE THREAD

**Issue by oguzhanbsolak** [Analog-Devices-MSDK/msdk#785]
Hi,

For the upcoming MAX78002EVKIT facial recognition demo, we need to use nearly 30 touchscreen buttons.
Is it possible to update, the default number for tsc2046.h TS_MAX_BUTTONS numbers to 32?

Regards,
Oguzhan Buyuksolak

**Comment by Jake-Carter** [comment]
Hi @oguzhanbsolak, we can support this.  I'll add the ability to change this compiler definition per-project.

**Comment by Jake-Carter** [comment]
@oguzhanbsolak FYI this is also merged.  See the PR description above - this one is implemented with a simpler compiler definition.
