### ISSUE TITLE
Issues with ternary operator & operator precedence in Cordio

### ISSUE THREAD

**Issue by sullivanmj** [Analog-Devices-MSDK/msdk#801]
I was running a static code analyzer on my project and it produced warnings that there are a few places in Cordio where there may be some bugs due to the ternary operator `?:` having a lower precedence than the addition operator `+`.

In each of these cases, the ternary operator should looks like it should be evaluated before the addition operator, but it is not.

https://github.com/Analog-Devices-MSDK/msdk/blob/4461e6d6383ac7e31285534e4e4e1a87531e5baf/Libraries/Cordio/controller/sources/ble/lctr/lctr_main_conn.c#L1568

https://github.com/Analog-Devices-MSDK/msdk/blob/4461e6d6383ac7e31285534e4e4e1a87531e5baf/Libraries/Cordio/controller/sources/ble/lctr/lctr_main_adv_master_ae.c#L1307

https://github.com/Analog-Devices-MSDK/msdk/blob/4461e6d6383ac7e31285534e4e4e1a87531e5baf/Libraries/Cordio/controller/sources/ble/lctr/lctr_int_adv_master_ae.h#L477

**Comment by Jake-Carter** [comment]
Thanks @sullivanmj, I've just opened a PR to add some extra parenthesis.

Let us know if your analyzer uncovers anything else

**Comment by sullivanmj** [comment]
No problem - that was the only thing it uncovered.
