### ISSUE TITLE
I2C Example Enhancement for MAX32690EVKIT

### ISSUE THREAD

**Issue by selimgullulu** [Analog-Devices-MSDK/msdk#824]
The I2C example fails to run by the default jumper settings on the MAX32690EVKIT. The reason for this is the Jumper 9 and Jumper10 are set to CTS and RTS by default on the EVKIT. These jumpers have to be set to SDA and SCL. 
The explanation in the main() can be extended with this information:
 printf("\n******** I2C Master-Slave Transaction Demo *********\n");
    printf("\nThis example uses one I2C peripheral as a master to\n");
    printf("read and write to another I2C which acts as a slave.\n");

    printf("\nYou will need to connect P1.8->P2.8 (SCL) and\n");
    printf("P1.7->P2.7 (SDA).\n");
    **printf("Make sure the Jumper 9 and Jumper 10 on the MAX32690EVKIT are set to SDA and SCL");_**
![MAX32690EVKIT_I2C_recovery](https://github.com/Analog-Devices-MSDK/msdk/assets/136325521/06665795-428e-4522-b192-0263050bdea6)

**Comment by Jake-Carter** [comment]
Thanks @selimgullulu, the [README](https://github.com/analogdevicesinc/MAX32xxx-MSDK/blob/main/Examples/MAX32690/I2C/README.md#required-connections) does highlight setting JP9/JP10, but I've just updated the printfs to make this more clear as well.

**Comment by selimgullulu** [comment]
Hi @Jake-Carter , thanks for the update!
