### ISSUE TITLE
uart_me15.c MXC_UART_Shutdown incorrect for UART3 (LPUART)

### ISSUE THREAD

**Issue by gavanfantom** [Analog-Devices-MSDK/msdk#886]
The following statement in MXC_UART_Shutdown() in uart_me15.c uses |= where it should clearly use &=. This will result in setting all irrelevant bits and leaving the relevant bits alone, rather than clearing the desired bits.

`        MXC_MCR->lppioctrl |= ~(MXC_F_MCR_LPPIOCTRL_LPUART0_RX | MXC_F_MCR_LPPIOCTRL_LPUART0_TX |
                                MXC_F_MCR_LPPIOCTRL_LPUART0_RTS | MXC_F_MCR_LPPIOCTRL_LPUART0_CTS);`

**Comment by Jake-Carter** [comment]
Thanks @gavanfantom
